# Generated by Django 5.0 on 2024-03-07 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1_telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='sessionUID',
            field=models.DecimalField(decimal_places=0, max_digits=22, unique=True),
        ),
    ]
