# Generated by Django 5.0 on 2024-04-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1_telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packetsession',
            name='timeOfDay',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
