# Generated by Django 5.0 on 2024-04-06 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1_telemetry', '0002_alter_packetsession_timeofday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmotion',
            name='worldForwardDirX',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='carmotion',
            name='worldForwardDirY',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='carmotion',
            name='worldForwardDirZ',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='carmotion',
            name='worldRightDirX',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='carmotion',
            name='worldRightDirY',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='carmotion',
            name='worldRightDirZ',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
