# Generated by Django 5.0 on 2024-03-08 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f1_telemetry', '0003_alter_header_sessionuid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarMotionData',
            new_name='CarMotion',
        ),
        migrations.RenameModel(
            old_name='CarSetupData',
            new_name='CarSetup',
        ),
        migrations.RenameModel(
            old_name='CarTelemetryData',
            new_name='CarTelemetry',
        ),
        migrations.RenameModel(
            old_name='LapData',
            new_name='Lap',
        ),
    ]
