# Generated by Django 5.0 on 2024-04-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1_telemetry', '0003_alter_carmotion_worldforwarddirx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='session_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField(default=0)),
                ('session_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='packetsession',
            name='seasonLinkIdentifier',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='packetsession',
            name='weekendLinkIdentifier',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
