# Generated by Django 5.0 on 2024-03-08 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1_telemetry', '0004_rename_carmotiondata_carmotion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aiControlled', models.BooleanField()),
                ('driverId', models.PositiveSmallIntegerField(default=9999)),
                ('teamId', models.PositiveSmallIntegerField()),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1_telemetry.header')),
            ],
        ),
        migrations.AddField(
            model_name='cartelemetry',
            name='driverId',
            field=models.ForeignKey(default=99999, on_delete=django.db.models.deletion.CASCADE, to='f1_telemetry.participant'),
            preserve_default=False,
        ),
    ]
