# Generated by Django 5.0 on 2024-03-08 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f1_telemetry', '0005_participant_cartelemetry_driverid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='header',
        ),
    ]
