# Generated by Django 5.0 on 2024-03-11 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1_telemetry', '0007_packetsessiondata'),
    ]

    operations = [
        migrations.AddField(
            model_name='lap',
            name='currentLapNum',
            field=models.PositiveSmallIntegerField(default=9999),
        ),
    ]
