# Generated by Django 5.0 on 2024-03-11 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1_telemetry', '0008_lap_currentlapnum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
