# Generated by Django 5.0 on 2024-03-20 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1_telemetry', '0009_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacketSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_weather', models.IntegerField()),
                ('m_trackTemperature', models.IntegerField()),
                ('m_airTemperature', models.IntegerField()),
                ('m_totalLaps', models.IntegerField()),
                ('m_trackLength', models.IntegerField()),
                ('m_sessionType', models.IntegerField()),
                ('m_trackId', models.IntegerField()),
                ('m_formula', models.IntegerField()),
                ('m_sessionTimeLeft', models.IntegerField()),
                ('m_sessionDuration', models.IntegerField()),
                ('m_pitSpeedLimit', models.IntegerField()),
                ('m_gamePaused', models.IntegerField()),
                ('m_isSpectating', models.IntegerField()),
                ('m_spectatorCarIndex', models.IntegerField()),
                ('m_sliProNativeSupport', models.IntegerField()),
                ('m_numMarshalZones', models.IntegerField()),
                ('m_zoneStart', models.FloatField()),
                ('m_zoneFlag', models.IntegerField()),
                ('m_safetyCarStatus', models.IntegerField()),
                ('m_networkGame', models.IntegerField()),
                ('m_numWeatherForecastSamples', models.IntegerField()),
                ('m_timeOffset', models.IntegerField()),
                ('m_trackTemperatureChange', models.IntegerField()),
                ('m_airTemperatureChange', models.IntegerField()),
                ('m_rainPercentage', models.IntegerField()),
                ('m_forecastAccuracy', models.IntegerField()),
                ('m_aiDifficulty', models.IntegerField()),
                ('m_seasonLinkIdentifier', models.PositiveIntegerField()),
                ('m_weekendLinkIdentifier', models.PositiveIntegerField()),
                ('m_sessionLinkIdentifier', models.PositiveIntegerField()),
                ('m_pitStopWindowIdealLap', models.IntegerField()),
                ('m_pitStopWindowLatestLap', models.IntegerField()),
                ('m_pitStopRejoinPosition', models.IntegerField()),
                ('m_steeringAssist', models.IntegerField()),
                ('m_brakingAssist', models.IntegerField()),
                ('m_gearboxAssist', models.IntegerField()),
                ('m_pitAssist', models.IntegerField()),
                ('m_pitReleaseAssist', models.IntegerField()),
                ('m_ERSAssist', models.IntegerField()),
                ('m_DRSAssist', models.IntegerField()),
                ('m_dynamicRacingLine', models.IntegerField()),
                ('m_dynamicRacingLineType', models.IntegerField()),
                ('m_gameMode', models.IntegerField()),
                ('m_ruleSet', models.IntegerField()),
                ('m_timeOfDay', models.PositiveIntegerField()),
                ('m_sessionLength', models.IntegerField()),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1_telemetry.header')),
            ],
        ),
        migrations.DeleteModel(
            name='PacketSessionData',
        ),
    ]
