# Generated by Django 5.0 on 2024-03-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1_telemetry', '0011_carmotion_worldforwarddirx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lap',
            name='currentLapNum',
            field=models.PositiveIntegerField(default=9999),
        ),
    ]
