# Generated by Django 5.0 on 2024-03-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1_telemetry', '0012_alter_lap_currentlapnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lap',
            name='sector1TimeInMS',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='lap',
            name='sector2TimeInMS',
            field=models.PositiveIntegerField(),
        ),
    ]
