from f1_22_telemetry.listener import TelemetryListener

listener = TelemetryListener(port=20777, host='localhost')
packet = listener.get()

# TRUNCATE TABLE f1_telemetry_carmotion, f1_telemetry_carsetup, f1_telemetry_cartelemetry, f1_telemetry_header, f1_telemetry_lap, f1_telemetry_log, f1_te
# lemetry_packetsession, f1_telemetry_participant RESTART IDENTITY;

# {'weather': 253, 
#  'trackTemperature': -32, 
#  'airTemperature': 62, 
#  'totalLaps': 1, 
#  'trackLength': 5408, 
#  'sessionType': 61, 
#  'trackId': 3, 
#  'formula': 0, 
#  'sessionTimeLeft': 0, 
#  'sessionDuration': 600, 
#  'pitSpeedLimit': 80, 
#  'gamePaused': 0, 
#  'isSpectating': 0, 
#  'spectatorCarIndex': 255, 
#  'sliProNativeSupport': 0, 
#  'numMarshalZones': 17,
#  'zoneStart': 0.9542952179908752, 
#  'zoneFlag': 0, 
#  'safetyCarStatus': 99, 
#  'networkGame': 71, 
#  'numWeatherForecastSamples': 220, 
#  'timeOffset': 0, 
#  'trackTemperatureChange': 48, 
#  'airTemperatureChange': 0, 
#  'rainPercentage': 120, 
#  'forecastAccuracy': 238, 
#  'aiDifficulty': 129, 
#  'seasonLinkIdentifier': 661651518, 
#  'weekendLinkIdentifier': 1728069284, 
#  'sessionLinkIdentifier': 4109423, 
#  'pitStopWindowIdealLap': 56, 
#  'pitStopWindowLatestLap': 154, 
#  'pitStopRejoinPosition': 193, 
#  'steeringAssist': 62, 
#  'brakingAssist': 0, 
#  'gearboxAssist':192, 
#  'pitAssist': 251, 
#  'pitReleaseAssist': 210, 
#  'ERSAssist': 62, 
#  'DRSAssist': 0, 
#  'dynamicRacingLine': 134,
#  'dynamicRacingLineType': 1, 
#  'gameMode': 228, 
#  'ruleSet': 62, 
#  'timeOfDay': 4152684288, 
#  'sessionLength': 62}
